### ISSUE TITLE
HEAD failed with exit status 128

### ISSUE THREAD

**Issue by Shpigford** [stackmystack/tsdl#5] opened 2024-09-28 16:17 UTC
I'm getting this error on a lot of parsers.

In this particular example, I have this for `yaml` in the parsers.toml file:

```
yaml = { ref="7b03feefd36b5f155465ca736c6304aca983b267", from = "https://github.com/tree-sitter-grammars/tree-sitter-yaml"}
```

Command line output:
```
Error:   × yaml: Could not clone to /Users/username/Development/tree-sitter/tmp/yaml
  ╰─▶ [tmp/yaml] git rev-parse HEAD failed with exit status 128.
      StdOut:
      HEAD
      StdErr:
      fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
```

Many parsers work correctly, but there's a handful that I can't get to run as they all fail with that status 128 error.

**Comment by stackmystack** [comment] 2024-10-21 10:18
Hi, sorry for the late reply, I was on vacations.

I will take a look asap, but it looks like the cloning part went wrong. Did you try again ever since? In a clean dir? Or maybe just delete the `--build-dir` (normally `tmp` under `cwd`)?

**Comment by stackmystack** [comment] 2024-10-21 10:35
Also, could you please give me your config file so I could replicate + see which parsers are not working?

**Comment by stackmystack** [comment] 2024-10-24 10:31
@Shpigford I tested it locally and it worked.

I am now more convinced it was a problem in cloning that put the repo in a weird state.

Could you please confirm ? Or at least send me the full `parsers.toml` file, give me more information on your machine, the # of CPUs (because `tsdl` downloads in parallel), etc. any info on how to reproduce is appreciated.

**Comment by stackmystack** [comment] 2024-10-24 10:32
What you can do is either pass the `--fresh` arg, to force a delete of the out dir … may not be suitable for all cases, but it's there.

**Comment by stackmystack** [comment] 2024-11-07 16:12
@Shpigford are you still facing problems? Can I close this issue?

**Comment by bugabinga** [comment] 2024-11-18 07:31
This usually happens when adding a parser with non-existent `ref` to `parsers.toml`, building, then correcting `ref` and/or `from` and building again. The first build seems to create a tempdir for the parser repo, which is empty. The second build maybe skips cloning, because the tempdir already exists?

Using `fresh = true` or `--fresh` or manually deleting the tempdir work around the problem.

Suggestions for a fix:

- check if tempdir for parser is empty before the clone and delete it if true
- improve error message, because `Could not clone to ...` is misleading, but maybe this is obsoleted by the first point?

**Comment by stackmystack** [comment] 2024-11-21 10:28
Thanks @bugabinga for the feedback.

I made a https://github.com/stackmystack/tsdl/pull/12 to specifically address this issue.
I hope it covers it. I would have preferred not to hope, but to actually cover and fix it, but I am not able to reporduce manually and add it to the test case.

If you got a specific set of instructions I can follow, it would be great.

I will let you know when I make a new release (which should be today).

**Comment by stackmystack** [comment] 2024-11-21 15:39
I release v1.3.0 which contains these fixes. Please let me know if it addresses the issues you raised here.

**Comment by bugabinga** [comment] 2024-11-21 21:13
Issue is fixed for me. Good job!

**Closed** 2024-11-22 15:03 UTC
